{{- if .Values.mongo.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sorry-cypress-helm.fullname" . }}-mongo
spec:
  ports:
  - name: "27017"
    port: {{ .Values.mongo.service.port }}
    targetPort: {{ .Values.mongo.service.port }}
  selector:
    app: {{ include "sorry-cypress-helm.fullname" . }}-mongo
{{- end }}