apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sorry-cypress-helm.fullname" . }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sorry-cypress-helm.fullname" . }}-mongo
  template:
    metadata:
      labels:
        app: {{ include "sorry-cypress-helm.fullname" . }}-mongo
      name: {{ include "sorry-cypress-helm.fullname" . }}-mongo
    spec:
      containers:
      - image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
        name: {{ include "sorry-cypress-helm.fullname" . }}-mongo
        ports:
        - containerPort: 27017
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.adminCommand('ping')
          failureThreshold: 6
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          {{- toYaml .Values.mongo.resources | nindent 10 }}
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: mongo-storage
        {{- if .Values.mongo.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "sorry-cypress-helm.fullname" . }}-mongo-storage-claim
        {{- else }}
          emptyDir: {}
        {{- end }}