apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sorry-cypress-helm.fullname" . }}-api
  labels:
    {{- include "sorry-cypress-helm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sorry-cypress-helm.fullname" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "sorry-cypress-helm.fullname" . }}-api
      name: {{ include "sorry-cypress-helm.fullname" . }}-api
    spec:
      containers:
      - env:
        - name: MONGODB_DATABASE
          value: sorry-cypress
        - name: MONGODB_URI
          value: mongodb://{{ include "sorry-cypress-helm.fullname" . }}-mongo:{{ .Values.mongo.service.port }}
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        name: {{ include "sorry-cypress-helm.fullname" . }}-api
        ports:
        - containerPort: 4000
        resources:
          {{- toYaml .Values.api.resources | nindent 10 }}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null